### ISSUE TITLE
Suggestion for more testable bots

### ISSUE THREAD

**Issue by meadsteve** [willrax/marvin#5]
So after your talk on Wednesday (great work by the way) I was thinking on some of the comments on how to make this more testable. One idea that was mentioned was having handle work in a more purely functional way so that it always returns a value and then something else dispatches those messages. 

So this would look something like:

``` elixir
  def handle_message(message, slack) do
    {:ok, {:send_message, "hello"}}
  end
```

I realised this would mean you'd lose the ability to send the typing message which seemed a shame so my next extension would be that the function returns a 2 or 3 tuple. With a 3 tuple the last part would be a function so the calling code can recurse until a 2 tuple is returned:

``` elixir
  def handle_message(message, slack) do
    {:ok, {:typing}, &next_message/2}
  end

  def next_message(message, slack) do
    {:ok, {:send_message, "hello"}}
  end
```

This means you could test each message in the chain in a purely functional way and assert that it returns the function defining the next step.

What do you think?

**Comment by lpil** [comment]
My first thought is to use a mock service for that like was also suggested at the meetup, like in the recent Plataformatec blog.

The solution I was suggesting does kinda presume there's a single response, doesn't it?

Another solution might be to pass in a connection struct that you can interact with directly, like Plug does. So you would call the typing function on that connection structure. Then in each one of your tests you can pass in a mock connection object. I think I'd probably try this. :)

**Comment by meadsteve** [comment]
@lpil yeah I think you're on the money with the connection/config struct. You could have something like:
`def handle_message(message, slack, config)`
and get any external services you needed from the config.

works well with what I suggested above to. The main reason I suggested the approach above was I thought the `typing` notification in the demo really humanised the bot. Which I liked.

**Comment by willrax** [comment]
Hey, sorry, I completely missed these messages for some reason. Testing is definitely the next thing I want to tackle before adding any other features (don't want to break anything).

On a local branch, I've been playing around with the mock service approach to mimic a slack connection. I think the tests for Phoenix channels are pretty nice and have a similar type of setup.

**Comment by meadsteve** [comment]
Hey @willrax no problem at all. Just wanted to throw some suggestions out that might've helped. I've been on paternity leave the last 2 weeks in any case. So I doubt I'd have seen your reply if you'd sent it earlier!
