### ISSUE TITLE
Elixir 1.3 requires HTTPotion 3.0

### ISSUE THREAD

**Issue by mirekm** [willrax/marvin#6]
I'm not an Elixir expert but it seems that Marvin depends on HTTPotion 2.2.2 which is incompatible with Elixir 1.3. I see the following error trying to run Marvin app:

```
==> httpotion
Compiling 1 file (.ex)

== Compilation error on file lib/httpotion.ex ==
** (ArgumentError) Access is not a protocol
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    lib/httpotion.ex:292: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by willrax** [comment]
Hi @mirekm, sorry about this. I'm fixing it up now and will create a new release.
